// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSession():Promise<void>;

export function GetAgentDetail(arg1:string):Promise<main.AgentDetailInfo>;

export function GetAgentStatuses():Promise<Array<main.AgentStatusInfo>>;

export function GetContract():Promise<string>;

export function GetIdea(arg1:string):Promise<string>;

export function GetLocks():Promise<Record<string, string>>;

export function InitProject(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<void>;

export function RespondPermission(arg1:string,arg2:boolean):Promise<void>;

export function RunLeadSession(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function UpdateIdea(arg1:string,arg2:string):Promise<void>;
