// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecutePlan() {
  return window['go']['main']['App']['ExecutePlan']();
}

export function GetAgentDetail(arg1) {
  return window['go']['main']['App']['GetAgentDetail'](arg1);
}

export function GetAgentStatuses() {
  return window['go']['main']['App']['GetAgentStatuses']();
}

export function GetContract() {
  return window['go']['main']['App']['GetContract']();
}

export function GetIdea(arg1) {
  return window['go']['main']['App']['GetIdea'](arg1);
}

export function GetLocks() {
  return window['go']['main']['App']['GetLocks']();
}

export function InitProject(arg1) {
  return window['go']['main']['App']['InitProject'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PlanRequest(arg1) {
  return window['go']['main']['App']['PlanRequest'](arg1);
}

export function RunLeadSession(arg1) {
  return window['go']['main']['App']['RunLeadSession'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SubmitRequest(arg1) {
  return window['go']['main']['App']['SubmitRequest'](arg1);
}

export function UpdateIdea(arg1, arg2) {
  return window['go']['main']['App']['UpdateIdea'](arg1, arg2);
}
